# Generated by Django 6.1.1 on 2026-10-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='embedding',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
